"""
Configuration for the timeseries waveform detection path.
"""

TS_STRIDE_FRAMES = 3
TS_FIXED_ROI_LEFT_RATIO = 0.08
TS_FIXED_ROI_RIGHT_RATIO = 0.88
TS_FIXED_ROI_TOP_RATIO = 0.55
TS_FIXED_ROI_BOTTOM_RATIO = 0.92
TS_FIXED_ROI_INNER_TOP_RATIO = 0.02
TS_FIXED_ROI_INNER_BOTTOM_RATIO = 0.82
TS_FIXED_ROI_SPLITS_ORANGE = (1.0, 0.6, 0.4)
TS_FIXED_ROI_SPLITS_WHITE = (1.0, 0.6)
TS_BLACK_THRESHOLD = 35
TS_WHITE_THRESHOLD = 200
TS_COLOR_ORANGE_H_MAX = 40
TS_COLOR_ORANGE_S_MIN = 70
TS_COLOR_ORANGE_V_MIN = 80
TS_MIN_COL_COUNT_PX = 3
TS_MIN_COL_COUNT_RATIO = 0.02
TS_BLACK_GATE_ORANGE_MIN = 0.70
TS_BLACK_GATE_WHITE_MIN = 0.55
TS_WHITE_ROW_MAX_MIN = 0.35
TS_WHITE_ROW_MAX_STRONG = 0.70
TS_ORANGE_BLACK_RATIO_MIN = 0.70
TS_WHITE_BLACK_RATIO_MIN = 0.50
TS_TOP_BLACK_HEIGHT_RATIO = 0.25
TS_TOP_BLACK_GATE_MIN = 0.80
TS_BLACK_RATIO_MIN_ANY = 0.20
TS_WHITE_SPLIT_BLACK_MIN = 0.25
TS_WHITE_COVERAGE_MIN = 0.10
TS_BASELINE_MIN_RATIO = 0.08
TS_BASELINE_BRIGHT_ROW_THRESHOLD = 150
TS_BASELINE_BRIGHT_ROW_THRESHOLD_RELAXED = 130
TS_BASELINE_BLACK_THRESHOLD = 50
TS_BASELINE_BLACK_MIN_RATIO = 0.08
TS_BASELINE_MAX_MEAN_DIFF = 70
TS_BASELINE_BAND_PX = 18
TS_BASELINE_ROW_SMOOTH_WINDOW = 9
TS_BASELINE_SEARCH_TOP_RATIO = 0.52
TS_BASELINE_SEARCH_BOTTOM_RATIO = 0.92
TS_SMOOTH_WINDOW = 9
TS_ORANGE_S_MIN = 150
TS_ORANGE_V_MIN = 150
TS_ORANGE_MIN_ON = 0.035
TS_ORANGE_MIN_OFF = 0.022
TS_WHITE_MIN_ON = 0.050
TS_WHITE_MIN_OFF = 0.030
TS_ORANGE_MIN_SEGMENT_SEC = 0.8
TS_WHITE_MIN_SEGMENT_SEC = 0.6
TS_MERGE_GAP_SEC = 0.5
TS_MAX_SEGMENT_SEC = 30.0
TS_SHORT_SEGMENT_SEC = 2.0
TS_SHORT_BLACK_RATIO_MIN = 0.42
TS_SHORT_ORANGE_PEAK_MIN = 0.0025
TS_SHORT_ORANGE_MEAN_MIN = 0.08
TS_SHORT_WHITE_PEAK_MIN = 0.006
TS_ORANGE_SUPPRESS_WHITE_THRESHOLD = 0.010
TS_HYSTERESIS_HIGH_Q = 0.995
TS_HYSTERESIS_ON_SCALE = 0.55
TS_HYSTERESIS_OFF_SCALE = 0.40

# Legacy baseline helper uses a symmetric horizontal crop.
TS_ROI_X_MARGIN = 0.08

__all__ = [name for name in globals() if name.startswith("TS_")]
